# Generated by Django 4.1.12 on 2024-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Urgent", "Urgent"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                    ("Routine", "Routine"),
                ],
                max_length=20,
            ),
        ),
    ]
